### ISSUE TITLE
Fix for wires not saving in multiple segments

### ISSUE THREAD

**Issue by MegaIng** [Stuffe/save_monger#2]
Proposed fix for https://github.com/Turing-Complete-Game/Suggestions-and-Issues/issues/301

https://github.com/Stuffe/save_monger/blob/51725f3885ae1ee79bec2df0eb6ae12e186e1dcc/save_monger.nim#L576

This should actually be just `while length < max_length:`, and the `max_length` calculation a few lines above should be changed to `let max_length = min(path.high - offset, 0b0001_1111)`

Currently, once the length of 31 is reached, the offset is always larger than max_length and so only length 1 segments are generated.

**Comment by Stuffe** [comment]
Thanks for the fix!
