### ISSUE TITLE
Level name <-> id mapping

### ISSUE THREAD

**Issue by al13n321** [Stuffe/save_monger#3]
`selected_programs` seems to be keyed by an integer level id. But in the game's save files (both schematics and `progress.dat`) only level names are used, not ids. Is there a mapping between names and ids available somewhere? Would it make sense to include it in this library as an enum or a map?

(Useful for external simulators/compilers, to be able to run the circuit as it's configured in the game, without having to specify program name separately. Especially if the circuit has multiple program components with different programs selected; idk if anyone actually does that, but no reason to not support it.)

**Comment by Stuffe** [comment]
Sorry I only see this now, but you can find the level IDs here: view-source:https://turingcomplete.game/api_level_meta

I might restructure this to include the level name enum directly at some point though.
